/**
 * Legacy Format Migrator
 *
 * Migrates from old 3-file format to new single AX.md format:
 * - .ax-{provider}/CUSTOM.md -> AX.md (merged)
 * - ax.index.json -> .ax/analysis.json (if deep analysis needed)
 * - ax.summary.json -> deprecated (embedded in AX.md)
 */

import * as fs from 'fs';
import * as path from 'path';
import { FILE_NAMES } from '../../constants.js';
import { getActiveConfigPaths } from '../../provider/config.js';

/** Result of migration */
export interface MigrationResult {
  success: boolean;
  newFile?: string;
  movedFiles?: string[];
  error?: string;
}

/** Options for migration */
export interface MigrationOptions {
  dryRun?: boolean;
  force?: boolean;
  verbose?: boolean;
}

/** Legacy format detection result */
export interface LegacyFormatDetection {
  hasLegacyFiles: boolean;
  files: string[];
  providerDirs: string[];
}

/**
 * Detect if project has legacy format files
 */
export function detectLegacyFormat(projectRoot: string): LegacyFormatDetection {
  const files: string[] = [];
  const providerDirs: string[] = [];

  // Check for provider-specific directories
  const providerDirPatterns = ['.ax-cli', '.ax-grok', '.ax-glm'];
  for (const dir of providerDirPatterns) {
    const dirPath = path.join(projectRoot, dir);
    if (fs.existsSync(dirPath) && fs.statSync(dirPath).isDirectory()) {
      providerDirs.push(dir);

      // Check for CUSTOM.md in provider dir
      const customMdPath = path.join(dirPath, 'CUSTOM.md');
      if (fs.existsSync(customMdPath)) {
        files.push(path.join(dir, 'CUSTOM.md'));
      }
    }
  }

  // Check for root-level legacy files
  const legacyRootFiles = ['ax.index.json', 'ax.summary.json'];
  for (const file of legacyRootFiles) {
    if (fs.existsSync(path.join(projectRoot, file))) {
      files.push(file);
    }
  }

  return {
    hasLegacyFiles: files.length > 0,
    files,
    providerDirs,
  };
}

/**
 * Migrate from legacy 3-file format to single AX.md
 */
export async function migrateFromLegacyFormat(
  projectRoot: string,
  options: MigrationOptions = {}
): Promise<MigrationResult> {
  const { dryRun = false, force = false, verbose = false } = options;

  // Detect legacy format
  const legacy = detectLegacyFormat(projectRoot);
  if (!legacy.hasLegacyFiles) {
    return {
      success: false,
      error: 'No legacy files detected. Nothing to migrate.',
    };
  }

  // Check if AX.md already exists
  const axMdPath = path.join(projectRoot, FILE_NAMES.AX_MD);
  if (fs.existsSync(axMdPath) && !force) {
    return {
      success: false,
      error: 'AX.md already exists. Use --force to overwrite.',
    };
  }

  const movedFiles: string[] = [];

  try {
    // Find the best CUSTOM.md to use as base
    let customMdContent = '';
    const activeConfigPaths = getActiveConfigPaths();
    const preferredDir = activeConfigPaths.DIR_NAME;

    // Try preferred provider dir first
    const preferredCustomMd = path.join(projectRoot, preferredDir, 'CUSTOM.md');
    if (fs.existsSync(preferredCustomMd)) {
      customMdContent = fs.readFileSync(preferredCustomMd, 'utf-8');
      if (verbose) {
        console.log(`Using ${preferredDir}/CUSTOM.md as base`);
      }
    } else {
      // Try other provider dirs
      for (const dir of legacy.providerDirs) {
        const customMdPath = path.join(projectRoot, dir, 'CUSTOM.md');
        if (fs.existsSync(customMdPath)) {
          customMdContent = fs.readFileSync(customMdPath, 'utf-8');
          if (verbose) {
            console.log(`Using ${dir}/CUSTOM.md as base`);
          }
          break;
        }
      }
    }

    // Clean up the content - remove hardcoded automatosx paths
    const cleanedContent = cleanLegacyContent(customMdContent);

    // Add metadata header
    const now = new Date().toISOString().split('T')[0];
    const axMdContent = `<!--
Generated by: ax-cli / ax-grok (migrated from legacy format)
Last updated: ${now}
Refresh: Run \`/init\` or \`ax init --refresh\` to update
-->

${cleanedContent}`;

    if (dryRun) {
      return {
        success: true,
        newFile: FILE_NAMES.AX_MD,
        movedFiles: legacy.files,
      };
    }

    // Create .ax/legacy directory for backup
    const legacyBackupDir = path.join(projectRoot, FILE_NAMES.UNIFIED_CONFIG_DIR, 'legacy');
    if (!fs.existsSync(legacyBackupDir)) {
      fs.mkdirSync(legacyBackupDir, { recursive: true });
    }

    // Move legacy files to backup
    for (const file of legacy.files) {
      const srcPath = path.join(projectRoot, file);
      const destPath = path.join(legacyBackupDir, path.basename(file));

      if (fs.existsSync(srcPath)) {
        // Copy to backup
        fs.copyFileSync(srcPath, destPath);
        // Remove original
        fs.unlinkSync(srcPath);
        movedFiles.push(file);
      }
    }

    // Remove empty provider directories
    for (const dir of legacy.providerDirs) {
      const dirPath = path.join(projectRoot, dir);
      if (fs.existsSync(dirPath)) {
        const remaining = fs.readdirSync(dirPath);
        if (remaining.length === 0) {
          fs.rmdirSync(dirPath);
        }
      }
    }

    // Write new AX.md
    fs.writeFileSync(axMdPath, axMdContent, 'utf-8');

    // If ax.index.json existed, copy to .ax/analysis.json
    const legacyIndexPath = path.join(legacyBackupDir, 'ax.index.json');
    if (fs.existsSync(legacyIndexPath)) {
      const analysisPath = path.join(projectRoot, FILE_NAMES.UNIFIED_CONFIG_DIR, FILE_NAMES.ANALYSIS_JSON);
      fs.copyFileSync(legacyIndexPath, analysisPath);
    }

    return {
      success: true,
      newFile: FILE_NAMES.AX_MD,
      movedFiles,
    };

  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown migration error',
    };
  }
}

/**
 * Clean legacy content - remove hardcoded automatosx paths and generic DO/DON'Ts
 */
function cleanLegacyContent(content: string): string {
  // Remove the entire "Project File Organization" section with automatosx paths
  const fileOrgPattern = /## 📁 Project File Organization[\s\S]*?(?=##|$)/;
  let cleaned = content.replace(fileOrgPattern, '');

  // Remove generic DO/DON'T sections that are too verbose
  const genericPatterns = [
    /❌ \*\*DON'T:\*\*\s*\n```[\s\S]*?```\n?/g,
    /✅ \*\*DO:\*\*\s*\n```[\s\S]*?```\n?/g,
  ];

  for (const pattern of genericPatterns) {
    // Only remove if the section is very long (indicates boilerplate)
    cleaned = cleaned.replace(pattern, (match) => {
      return match.length > 500 ? '' : match;
    });
  }

  // Remove references to automatosx directories
  cleaned = cleaned.replace(/automatosx\/PRD\//g, '');
  cleaned = cleaned.replace(/automatosx\/REPORT\//g, '');
  cleaned = cleaned.replace(/automatosx\/tmp\//g, '');
  cleaned = cleaned.replace(/\.\/automatosx\//g, '');

  // Remove multiple consecutive empty lines
  cleaned = cleaned.replace(/\n{4,}/g, '\n\n\n');

  // Remove trailing section separators
  cleaned = cleaned.replace(/---\s*$/g, '');

  return cleaned.trim();
}

/**
 * Check if migration is recommended
 */
export function shouldRecommendMigration(projectRoot: string): boolean {
  const legacy = detectLegacyFormat(projectRoot);
  const hasAxMd = fs.existsSync(path.join(projectRoot, FILE_NAMES.AX_MD));

  // Recommend migration if has legacy files but no AX.md
  return legacy.hasLegacyFiles && !hasAxMd;
}
